# Generated by Django 4.1.2 on 2022-10-27 05:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
import utils.time


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_time", models.DateTimeField(default=utils.time.get_now)),
                ("last_updated_time", models.DateTimeField(default=utils.time.get_now)),
                ("title", models.CharField(max_length=200)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Subdivision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_time", models.DateTimeField(default=utils.time.get_now)),
                ("last_updated_time", models.DateTimeField(default=utils.time.get_now)),
                ("title", models.CharField(max_length=200)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mytree.subdivision",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_time", models.DateTimeField(default=utils.time.get_now)),
                ("last_updated_time", models.DateTimeField(default=utils.time.get_now)),
                ("name", models.CharField(max_length=200)),
                (
                    "employment_date",
                    models.DateTimeField(default=datetime.datetime.now),
                ),
                ("salary", models.FloatField(null=True)),
                (
                    "job_title",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mytree.job",
                    ),
                ),
                (
                    "subdivision",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mytree.subdivision",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
