# Generated by Django 4.1.2 on 2022-10-29 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mytree", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subdivision",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nodes",
                to="mytree.subdivision",
            ),
        ),
    ]
